sudo: false

language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - composer self-update
  - rm -rf composer.lock
  - composer install --no-interaction --dev

script:
  - vendor/bin/phpunit
