sudo: false

language: php

php:
  - 5.5.9

install:
  - cp .env.travis .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
