title: Speak Like A Brazilian
description: >- # this means to ignore newlines until "baseurl:"
  Learn how to speak like a Brazilian, using local expressions!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: speaklikeabr
github_username:  tupilabs
author: Bruno P. Kinoshita

markdown: kramdown
theme: minima

include:
  - a

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - docs/
 - .idea/
