title: Speak Like A Brazilian
description: >- # this means to ignore newlines until "baseurl:"
  Learn how to speak like a Brazilian, using local expressions!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: speaklikeabr
github_username:  tupilabs
author: Bruno P. Kinoshita

gems: [jekyll-paginate-v2]

markdown: kramdown
theme: minima

include:
  - expressions

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - docs/
 - .idea/

plugins:
- jekyll-paginate-v2

collections:
 expressions:
  output: true
  permalink: /:path/

pagination:
 enabled: true
 debug: false
 collection: 'posts'
 per_page: 10
 permalink: '/page/:num/'
 title: ':title - page :num'
 limit: 0
 sort_field: 'date'
 sort_reverse: true
 category: 'posts'
 tag: ''
 locale: ''
 trail:
  before: 2
  after: 2
 extension: html
 indexpage: 'index'
